# https://dev.azure.com/dylan-hasler

resources:
  repositories:
    - repository: templates
      type: github
      name: ThePicklenat0r/templates
      endpoint: ThePicklenat0r

trigger:
  tags:
    include:
      - '*'
pr: none

variables:
  - name: versionBuilder
    value: '6.6'
  - group: docker
  - group: github

stages:
- template: /azp/hassio-addons/azp-release-addon.yml@templates
  parameters:
    addon: 'ngrok'
    arch: '--all'
